//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63134865.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatHang()
        {
            this.DonDatHangChiTiets = new HashSet<DonDatHangChiTiet>();
        }
    
        public string MaDDH { get; set; }
        public string SdtKH { get; set; }
        public string TinNhanDDH { get; set; }
        public string NgayGioDDH { get; set; }
        public string TrangThaiDDH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatHangChiTiet> DonDatHangChiTiets { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
