//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63134865.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLy
    {
        public string TkQL { get; set; }
        public string MkQL { get; set; }
        public string HoTenQL { get; set; }
        public string SdtQL { get; set; }
    }
}
