//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63134865.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.DonDatHangChiTiets = new HashSet<DonDatHangChiTiet>();
        }
    
        public string MaSP { get; set; }
        public Nullable<int> MaHSX { get; set; }
        public Nullable<int> MaLSP { get; set; }
        public string TenSP { get; set; }
        public string SizeSP { get; set; }
        public string GiaSP { get; set; }
        public Nullable<int> GiamGiaSP { get; set; }
        public string AnhSP { get; set; }
        public string CapNhatNgayThangSP { get; set; }
        public string MieuTaSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatHangChiTiet> DonDatHangChiTiets { get; set; }
        public virtual HangSanXuat HangSanXuat { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual TiLe TiLe { get; set; }
    }
}
