//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63134865.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiLe
    {
        public string MaSP { get; set; }
        public Nullable<int> TiLeSao { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
